name: Build to cachix

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'flake.lock'
      - '**.nix'
  workflow_run:
    workflows: ["Update flake.lock"]
    types:
      - completed

jobs:
  build:
    name: Build and push to cachix
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: max-jobs = 4
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with:
          name: pierreborine
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build nixvim
        run: nix build -L
