name: nixvim

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and cache
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            max-jobs = 4
      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with:
          name: pierreborine
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build nixvim
        run: |
          nix build -L github:PierreBorine/nixvim-config?rev=${{ github.sha }}
